server:
  port: 19090

spring:
  datasource:
    # secret-key는 환경변수로 설정
    url: jdbc:p6spy:mariadb://localhost:3306/heysodiary
    username: ENC(hQiz+S56g0lxwDtqy2pkFBIYalru1mZcmQv894o8uV5Ol2el+sH6tiGKQ7QdMDYP) # 사용자명 (예시)
    password: ENC(0rC5ohNoxi5U68zaKGRLL1wt0jSXeoMfyWLNlD9M9hWzMY0H/GGfWTGVCvy9Obuq) # 비밀번호 (예시)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB # 하나의 파일의 최대 사이즈
      max-request-size: 60MB # 한번의 요청으로 허용가능한 여러개 파일의 합계 사이즈
  mvc:
    log-request-details: true # 로그에 API 요청 파라미터까지 보도록 처리, 반드시 운영에서는 비활성화

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
      - classpath:db/seed
    # repair: true

# ★ datasource-proxy(데코레이터) 쪽 로깅은 전부 끔 (의존성은 유지)
decorator:
  datasource:
    enabled: false
    # 데코레이터 자체는 유지하되, 로깅 기능만 비활성화
    datasource-proxy:
      enabled: false
    p6spy:
      enable-logging: false

logging:
  level:
    p6spy: INFO
    com.p6spy: INFO
    # datasource-proxy가 혹시라도 남기는 로그 완전 차단
    # net.ttddyy.dsproxy: OFF
    # net.ttddyy.dsproxy.listener: OFF
    # MyBatis 자체 로그도 필요시 끌 수 있음(준비/파라미터 라인 방지용)
    org.apache.ibatis: INFO
    org.mybatis: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.web.servlet.error: DEBUG
    # org.springframework.web.multipart: DEBUG  # 파일 업로드 과정에서 발생하는 상세한 활동이나 문제점들을 추적
    # org.springframework.http.converter: DEBUG # 응답의 parameter가 직렬화 되는 과정을 로그로 볼때
